# Generated by Django 6.0.2 on 2026-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20)),
                ('bus_type', models.CharField(max_length=50)),
                ('total_seats', models.IntegerField()),
            ],
        ),
    ]
